name: build

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distro: humble
            docker_image: osrf/ros:humble-desktop
          - ros_distro: iron
            docker_image: osrf/ros:iron-desktop
          - ros_distro: jazzy
            docker_image: osrf/ros:jazzy-desktop
          - ros_distro: rolling
            docker_image: osrf/ros:rolling-desktop

    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y libboost-all-dev
      - name: Build
        shell: bash
        run: |
          source /opt/ros/${{ matrix.ros_distro }}/setup.sh
          colcon build